"""Server-owned opinion contract; market facts are never generated by the LLM."""
VERSION = "opinion-v93"

def paragraph():
    return {"type": "object", "additionalProperties": False,
            "properties": {"text": {"type": "string"},
                           "refs": {"type": "array", "items": {"type": "string"}}},
            "required": ["text", "refs"]}

SCHEMA = {"type": "object", "additionalProperties": False,
          "properties": {"decision": {"type": "string", "enum": ["可考慮買進", "等待", "避開", "資料不足"]},
                         **{name: paragraph() for name in ("support", "against", "conclusion", "risk")},
                         "action": {"type": "string"}, "invalidation": {"type": "string"}},
          "required": ["decision", "support", "against", "conclusion", "risk", "action", "invalidation"]}
