const fs=require('fs'),vm=require('vm'),a=require('node:assert/strict'),path=require('path');
const nodes=new Map(),storage=new Map();
const node=id=>{if(!nodes.has(id))nodes.set(id,{innerHTML:'',textContent:'',value:'',style:{},scrollIntoView(){}});return nodes.get(id)};
const c=vm.createContext({console,Date,document:{getElementById:node,addEventListener(){}},window:{},localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)}});
for(const f of ['app.js','short-term.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'..',f),'utf8'),c);
const ev=s=>vm.runInContext(s,c);
c.calendar=Array.from({length:15},(_,i)=>`2026-09-${String(i+1).padStart(2,'0')}`);
c.row={passed:true,date:'2026-09-01',signal_low:95,checks:[],bars:c.calendar.map(date=>({date,valid:true,open:100,close:100,high:101,low:99}))};
c.trade={date:'2026-09-06',price:100,stop:4,target:12,signal_date:'2026-09-01',signal_low:95};
let r=ev('shortTradeState(trade,row,calendar)');
a.equal(r.days,10);a.equal(r.stopPrice,96);a.ok(Math.abs(r.targetPrice-112)<1e-9);
a.ok(r.alerts.some(x=>x.includes('第3交易日')));a.ok(r.alerts.some(x=>x.includes('10個交易日')));
c.row.bars[7].low=94;c.row.bars[7].high=113;
a.ok(ev('shortTradeState(trade,row,calendar).alerts.some(x=>x.includes("先後"))'));
c.row.bars[7].valid=false;a.match(ev('shortTradeState(trade,row,calendar).error'),/不完整/);c.row.bars[7].valid=true;
c.trade.date='2026-08-01';a.match(ev('shortTradeState(trade,row,calendar).error'),/交易日/);
c.trade.date='';a.match(ev('shortTradeState(trade,row,calendar).error'),/等待/);
ev('shortPayload={data:{2330:row},calendar};state.universe={2330:{name:"台積電"}}');
ev('saveShortSignal("2330")');a.equal(ev('shortTrades()["2330"].signal_date'),'2026-09-01');
a.equal(ev('shortTrades()["2330"].horizon'),5);
c.trade.date='2026-09-11';c.trade.horizon=5;
a.ok(ev('shortTradeState(trade,row,calendar).alerts.some(x=>x.includes("5個交易日"))'));
c.trade.date='2026-09-12';
a.ok(!ev('shortTradeState(trade,row,calendar).alerts.some(x=>x.includes("持有期限"))'));
node('shortDate').value='2026-09-01';node('shortPrice').value='100';node('shortStop').value='4';node('shortTarget').value='12';
ev('saveShortTrade("2330")');a.match(node('shortMessage').textContent,/晚於訊號日/);
// Next day's data changes current signal; the saved signal must remain anchored.
c.row.date='2026-09-15';c.row.signal_low=120;c.row.passed=false;
node('shortDate').value='2026-09-06';ev('saveShortTrade("2330")');
a.equal(ev('shortTrades()["2330"].signal_low'),95);a.equal(ev('shortTrades()["2330"].date'),'2026-09-06');
a.equal(ev('shortTrades()["2330"].horizon'),5);
ev('removeShortTrade("2330")');a.equal(ev('Object.keys(shortTrades()).length'),0);
c.row.passed=true;c.row.entry={status:'風險偏高',reason:'距MA5超過5%'};
ev('renderShortTerm("risk")');a.match(node('screenerResult').innerHTML,/距MA5超過5%/);
ev('renderShortTerm("enter")');a.match(node('screenerResult').innerHTML,/此分類沒有股票/);
c.row.entry={status:'可以進場',reason:'已通過收盤風險條件'};
ev('renderShortTerm("enter")');a.match(node('screenerResult').innerHTML,/已通過收盤風險條件/);
ev('showShortStock("2330")');a.match(node('shortDetail').innerHTML,/可以進場/);
console.log('Short-term: persisted signal anchoring, next-session entry, cash levels, missing days, 3/10-day reminders and ambiguous daily touches passed');
